before_install:
  - whoami
  - echo $HOME
  - echo $PWD

install:
  # feature: json_linting, 1 line
  - npm install jsonlint -g

script:
  # feature: json_linting, 1 line
  - find . -name "*.json" -type f -exec jsonlint -q "{}" \; -exec /bin/echo "{}" \;
