on: push
jobs:
  name_or-jobid-no_spaces:
    runs-on: ubuntu-latest
    steps:
      - name: pwd meh.
        run: |
          echo meh.
          pwd
          ls -la
      - name: branch event tag
        run: |
          echo "ref: ${{ github.ref }}"
          echo "base_ref: ${{ github.base_ref }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "event: ${{ github.event }}"
          echo "event_name: ${{ github.event_name }}"
          echo "event.action: ${{ github.event.action }}"
          echo "..."
      - uses: actions/checkout@v2.3.4
      - name: grub da brunch frum ckott
        run: |
          echo ">>> git branch --contains ..."
          git branch --contains ${{ github.sha }} --format "%(refname)" | cat
          echo ">>> git reflog ..."
          git reflog show --all | grep ${{ github.sha }}
